//
// Created by Yurun SONG on 22/05/2019.
//
// Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
//
// If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:
//
// How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?


#ifndef Q21_30_Q29_H
#define Q21_30_Q29_H

#include <iostream>
#include <set>
#include <cmath>

using namespace std;

class Q29 {

public:
    Q29() {
        cout << "How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?" << endl;

    }

    // 2^(2~6) <= 100
    // 3^(2~4) <= 100
    // 4^(2~3) <= 100
    // 5^(2)   <= 100
    // 6^(2)   <= 100
    // ..
    // 10^(2)  <= 100

    void solver() {
        int items = 0;
        std::set<double> collection;

        for (int b = 2; b <= 100; ++b) {
            for (int a = 2; a <= 100; ++a) {
                double result = pow(a, b);
                collection.insert(result);
            }
        }

        cout << collection.size()<< endl;
    }

};


#endif //Q21_30_Q29_H
