import java.util.ArrayList;

/*
 Project Euler Problem 44
 Yurun SONG
 2019-09-16

 Problem 44:
    Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
        1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
    It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
    Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
   */
public class Q44 {

    Q44(){
        System.out.println("Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?");
    }

    /*
        Pa + Pb = [(3a^2-a) + (3b^-b)]/2
                = [3(a^2+b^2)-(a+b)]/2

        Pb - Pa = [(3b^2-b) - (3a^-a)]/2
                = [3(b^2-a^2)-(b-a)]/2

        |(a-b)(3a+3b-1)| , in which a&b >0, so a should try to equal b, a and b should be the smaller the better

        p(k+1) - Pk  = 3k+1

     */
    public void solver() {
        ArrayList<Integer> nums = new ArrayList<>();
        int n = 1;
        int Pn = 1;
        nums.add(Pn);

        while (true) {
            Pn += 3 * n + 1;
            nums.add(Pn);
            n++;

            for (int i = 0; i < nums.size(); i++) {
                int a = Pn - nums.get(i);
                int b = Pn + nums.get(i);

                if (isPentagonal(b) && isPentagonal(a)) {
                    System.out.println(a);
                    return;
                }

            }
        }
    }


    public boolean isPentagonal(int n){
        Double r = Math.sqrt(1+24*n);
        return (r+1)%6 == 0;
    }

    public static void main(String[] args) {
       new Q44().solver();
    }
}
