/*
 Project Euler Problem 45
 Yurun SONG
 2019-09-17

 Problem 45:
    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
        Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
        Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...

    It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

public class Q45 {

    Q45(){
        System.out.println("Find the next triangle number that is also pentagonal and hexagonal.");
    }

    public void solver(){
        int count = 0;
        int n = 144;
        while(count < 1) {

            long b = n*(2*n-1);

            if(isPentagonal(b) && isTriangle(b)){
                count++;
            }

            if(count == 1) {
                System.out.println(b);
            }
            n++;
        }
    }

    public boolean isPentagonal(long b){
        Double r = Math.sqrt(1+24*b);
        return (r+1)%6 == 0;
    }

    public boolean isTriangle(long b){
        Double r = Math.sqrt(1+8*b);
        return (r-1)%2 == 0;
    }

    public static void main(String[] args) {
        new Q45().solver();
    }
}
